//auth
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'

export const LOGOUT = 'LOGOUT'

//alerts
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

//seller
// export const ADD_CATEGORY='ADD_CATEGORY'
export const ADD_CATEGORY_SUCCESS='ADD_CATEGORY_SUCCESS'
export const ADD_CATEGORY_FAIL='ADD_CATEGORY_FAIL'

export const GET_CATEGORY_SUCCESS='GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAIL='GET_CATEGORY_SUCCESS'

// export const DELETE_CATEGORY='DELETE_CATEGORY'


