//auth
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'

export const LOGOUT = 'LOGOUT'

//alerts
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

//seller
//Add category
export const ADD_CATEGORY_SUCCESS='ADD_CATEGORY_SUCCESS'
export const ADD_CATEGORY_FAIL='ADD_CATEGORY_FAIL'

export const GET_CATEGORY_SUCCESS='GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAIL='GET_CATEGORY_FAIL'

// Delete category
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

// Update Category
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE";
//create Products
export const ADD_PRODUCTS_SUCCESS= "ADD_PRODUCTS_SUCCESS";
export const ADD_PRODUCTS_FAIL="ADD_PRODUCTS_FAIL"
//get all products
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL="GET_PRODUCTS_FAIL"

// Add new Product
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";
// Upload  Product
export const UPLOAD_PRODUCT_SUCCESS = "UPLOAD_PRODUCT_SUCCESS";
export const UPLOAD_PRODUCT_FAILURE = "UPLOAD_PRODUCT_FAILURE";

// Update Product
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

// Delete product
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

//Add categorypharmacy
export const ADD_PHARM_SUCCESS='ADD_PHARM_SUCCESS'
export const ADD_PHARM_FAIL='ADD_PHARM_FAIL'

export const GET_PHARM_SUCCESS='GET_PHARM_SUCCESS'
export const GET_PHARM_FAIL='GET_PHARM_FAIL'

// Delete categorypharmacy
export const DELETE_PHARM_SUCCESS = "DELETE_PHARM_SUCCESS";
export const DELETE_PHARM_FAILURE = "DELETE_PHARM_FAILURE";

// Update Categorypharmacy
export const UPDATE_PHARM_SUCCESS = "UPDATE_PHARM_SUCCESS";
export const UPDATE_PHARM_FAILURE = "UPDATE_PHARM_FAILURE";
//create Pharmacy
export const ADD_PHARMACY_SUCCESS= "ADD_PHARMACY_SUCCESS";
export const ADD_PHARMACY_FAILURE="ADD_PHARMACY_FAILURE"
//get all Pharmacy
export const GET_PHARMACY_SUCCESS="GET_PHARMACY_SUCCESS";
export const GET_PHARMACY_FAIL="GET_PHARMACY_FAIL"


// Upload  Pharmacy
export const UPLOAD_PHARMACY_SUCCESS = "UPLOAD_PHARMACY_SUCCESS";
export const UPLOAD_PHARMACY_FAILURE = "UPLOAD_PHARMACY_FAILURE";

// Update Pharmacy
export const UPDATE_PHARMACY_SUCCESS = "UPDATE_PHARMACY_SUCCESS";
export const UPDATE_PHARMACY_FAILURE = "UPDATE_PHARMACY_FAILURE";

// Delete Pharmacyproduct
export const DELETE_PHARMACY_SUCCESS = "DELETE_PHARMACY_SUCCESS";
export const DELETE_PHARMACY_FAILURE = "DELETE_PHARMACY_FAILURE";


//doctor
//Add hospital
export const ADD_HOSPITAL_SUCCESS='ADD_HOSPITAL_SUCCESS'
export const ADD_HOSPITAL_FAIL='ADD_HOSPITAL_FAIL'

export const GET_HOSPITAL_SUCCESS='GET_HOSPITAL_SUCCESS'
export const GET_HOSPITAL_FAIL='GET_HOSPITAL_FAIL'

// Delete hospital
export const DELETE_HOSPITAL_SUCCESS = "DELETE_HOSPITAL_SUCCESS";
export const DELETE_HOSPITAL_FAILURE = "DELETE_HOSPITAL_FAILURE";

// Update Hospital
export const UPDATE_HOSPITAL_SUCCESS = "UPDATE_HOSPITAL_SUCCESS";
export const UPDATE_HOSPITAL_FAILURE = "UPDATE_HOSPITAL_FAILURE";

// Doctor Profile
//create Profiles
export const ADD_PROFILES_SUCCESS= "ADD_PROFILES_SUCCESS";
export const ADD_PROFILES_FAIL="ADD_PROFILES_FAIL"
//get all profiles
export const GET_PROFILES_SUCCESS="GET_PROFILES_SUCCESS";
export const GET_PROFILES_FAIL="GET_PROFILES_FAIL"

// Add new Profile
export const ADD_PROFILE_SUCCESS = "ADD_PROFILE_SUCCESS";
export const ADD_PROFILE_FAILURE = "ADD_PROFILE_FAILURE";
// Upload  Profile
export const UPLOAD_PROFILE_SUCCESS = "UPLOAD_PROFILE_SUCCESS";
export const UPLOAD_PROFILE_FAILURE = "UPLOAD_PROFILE_FAILURE";

// Update Profile
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

// Delete profile
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";
export const DELETE_PROFILE_FAILURE = "DELETE_PROFILE_FAILURE";

//Lostpet
export const ADD_LOSTPET_SUCCESS= "ADD_LOSTPET_SUCCESS";
export const ADD_LOSTPET_FAIL="ADD_LOSTPET_FAIL"

export const GET_LOSTPET_SUCCESS="GET_LOSTPET_SUCCESS";
export const GET_LOSTPET_FAIL="GET_LOSTPET_FAIL"

export const UPLOAD_LOSTPET_SUCCESS = "UPLOAD_LOSTPET_SUCCESS";
export const UPLOAD_LOSTPET_FAILURE = "UPLOAD_LOSTPET_FAILURE";

export const UPDATE_LOSTPET_SUCCESS = "UPDATE_LOSTPET_SUCCESS";
export const UPDATE_LOSTPET_FAILURE = "UPDATE_LOSTPET_FAILURE";

export const DELETE_LOSTPET_SUCCESS = "DELETE_LOSTPET_SUCCESS";
export const DELETE_LOSTPET_FAILURE = "DELETE_LOSTPET_FAILURE";
//Appointment
export const ADD_APPOINTMENT_SUCCESS= "ADD_APPOINTMENT_SUCCESS";
export const ADD_APPOINTMENT_FAILURE="ADD_APPOINTMENT_FAILURE"